name: Deploy to ECR

on: 
  push:
    branches: [ master ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest
   
    env:
      APP_REPOSITORY: myapp
      DB_REPOSITORY: mydb
      APP_IMAGE_TAG: 0.1
      DB_IMAGE_TAG: 0.2

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        
      run: |
        cd clo835_fall2022_assignment1/
        ls -ltra
        # Docker build
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$APP_IMAGE_TAG .
        # Unit test
        docker run -d -p 80:8080 --name my-app $ECR_REGISTRY/$APP_REPOSITORY:$APP_IMAGE_TAG
        docker ps
        echo "Pause for 10 seconds to let container start"
        sleep 10
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$APP_IMAGE_TAG
        
    - name: Build, test, tag, and push image to Amazon ECR
     
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        
      run: |
        cd clo835_fall2022_assignment1/
        ls -ltra
        # Docker build
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$DB_IMAGE_TAG -f Dockerfile_mysql .
        # Unit test
        docker run -d --name my-db $ECR_REGISTRY/$DB_REPOSITORY:$DB_IMAGE_TAG
        docker ps
        echo "Pause for 10 seconds to let container start"
        sleep 10
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$DB_IMAGE_TAG
